name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - macos-11
          - macos-12

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: clone_golang
      run: git clone -b go1.17.8 --single-branch https://github.com/golang/go ../go
    - name: clone_python
      run: git clone -b v3.9.12 --single-branch https://github.com/python/cpython ../cpython
    - name: make_single_test
      run: make -j8 build/unittest_lang
    - name: single_test1
      run: build/unittest_lang golang_if_func_assoc2
    - name: single_test2
      run: build/unittest_lang calc
    - name: single_test3
      run: build/unittest_lang xfail_lexer_cycle
    - name: bootstrap
      run: ./bootstrap.sh
